version: "3"

services:
  client:
    container_name: web_client
    build:
      context: ./client
      dockerfile: Dockerfile
    image: meetup-app/client
    ports:
      - "8080:8080"
    expose:
      - "8080"
    volumes:
      - ./client
    links:
      - server

  server:
    container_name: web_server
    build:
      context: ./server
      dockerfile: Dockerfile
    image: meetup-app/server
    ports:
      - "5000:5000"
    expose:
      - "5000"
    volumes:
      - ./server
